options {
    IGNORE_CASE = true;
}

PARSER_BEGIN(Lexical_Analyzer)
public class Lexical_Analyzer {
    public static void main(String[] args) throws ParseException {
        Lexical_Analyzer parser = new Lexical_Analyzer(System.in);
        parser.Start();
    }
}
PARSER_END(Lexical_Analyzer)

/* For the regular expressions on the right, the token on the left will be returned: */

TOKEN : {
//Turbo Pascal reserved words
    //Palavras-chave de controle
    < IF: "if" >
    | < THEN: "then" >
    | < ELSE: "else" >
    | < BEGIN: "begin" >
    | < END: "end" >
    | < CASE: "case" >
    | < REPEAT: "repeat" >
    | < UNTIL: "until" >
    | < WHILE: "while" >
    | < FOR: "for" >
    | < TO: "to" >
    | < DOWNTO: "downto" >
    | < DO: "do" >

    //Declarações
    | < PROGRAM: "program" >
    | < VAR: "var" >
    | < CONST: "const" >
    | < TYPE: "type" >
    | < FUNCTION: "function" >
    | < PROCEDURE: "procedure" >
    | < UNIT: "unit" >
    | < USES: "uses" >

    //Operações e operadores booleanos/matemáticos
    | < DIV: "div" >
    | < MOD: "mod" >
    | < AND: "and" >
    | < OR: "or" >
    | < NOT: "not" >
    | < XOR: "xor" >
    | < SHL: "shl" >
    | < SHR: "shr" >

//Object Pascal reserved words
    | < AS: "as" >
    | < CLASS: "class" >
    | < DISPINTERFACE: "dispinterface" >
    | < EXCEPT: "except" >
    | < EXPORTS: "exports" >
    | < FINALIZATION: "finalization" >
    | < FINALLY: "finally" >
    | < INITIALIZATION: "initialization" >
    | < INLINE: "inline" >
    | < IS: "is" >
    | < LIBRARY: "library" >
    | < ON: "on" >
    | < OUT: "out" >
    | < PACKED: "packed" >
    | < PROPERTY: "property" >
    | < RAISE: "raise" >
    | < RESOURCESTRING: "resourcestring" >
    | < THREADVAR: "threadvar" >
    | < TRY: "try" >

//Label
    | < LABEL: "label" >

//Modifies (They are not exactly reserved words in the sense that they can be used as identifiers, but in specific places)
    | < ABSOLUTE: "absolute" >
    | < ABSTRACT: "abstract" >
    | < ALIAS: "alias" >
    | < ASSEMBLER: "assembler" >
    | < BITPACKED: "bitpacked" >
    | < BREAK: "break" >
    | < CDECL: "cdecl" >
    | < CONTINUE: "continue" >
    | < CPPDECL: "cppdecl" >
    | < CVAR: "cvar" >
    | < DEFAULT: "default" >
    | < DYNAMIC: "dynamic" >
    | < ENUMERATOR: "enumerator" >
    | < EXPORT: "export" >
    | < EXTERNAL: "external" >
    | < FAR: "far" >
    | < FAR16: "far16" >
    | < FORWARD: "forward" >
    | < GENERIC: "generic" >
    | < HELPER: "helper" >
    | < IMPLEMENTS: "implements" >
    | < INDEX: "index" >
    | < INTERRUPT: "interrupt" >
    | < IOCHECK: "iocheck" >
    | < LOCAL: "local" >
    | < MESSAGE: "message" >
    | < NAME: "name" >
    | < NEAR: "near" >
    | < NODEFAULT: "nodefault" >
    | < NORETURN: "noreturn" >
    | < NOSTACKFRAME: "nostackframe" >
    | < OLDFPCCALL: "oldfpccall" >
    | < OTHERWISE: "otherwise" >
    | < OVERLOAD: "overload" >
    | < OVERRIDE: "override" >
    | < PASCAL: "pascal" >
    | < PRIVATE: "private" >
    | < PROTECTED: "protected" >
    | < PUBLIC: "public" >
    | < PUBLISHED: "published" >
    | < READ: "read" >
    | < REGISTER: "register" >
    | < REINTRODUCE: "reintroduce" >
    | < RESULT: "result" >
    | < SAFECALL: "safecall" >
    | < SAVEREGISTERS: "saveregisters" >
    | < SOFTFLOAT: "softfloat" >
    | < SPECIALIZE: "specialize" >
    | < STATIC: "static" >
    | < STDCALL: "stdcall" >
    | < STORED: "stored" >
    | < STRICT: "strict" >
    | < UNALIGNED: "unaligned" >
    | < VARARGS: "varargs" >
    | < VIRTUAL: "virtual" >
    | < WINAPI: "winapi" >
    | < WRITE: "write" >

// Hint Directives (are Modifies too)
    | < DEPRECATED: "deprecated" >
    | < EXPERIMENTAL: "experimental" >
    | < PLATFORM: "platform" >
    | < UNIMPLEMENTED: "unimplemented" >

//Others

    // Intern Tokens
    | < #LETTER: ["a"-"z","A"-"Z"] >
    | < #LETTER_HEXADECIMAL: ["a"-"f","A"-"F"] >
    | < #DIGIT: ["0"-"9"] >
    | < #OCTAL_DIGIT: ["0"-"7"] >
    | < #BINARY_DIGIT: ["0"-"1"] >
    | < #SIGN: ["+"] | ["-"] >
    | < #SINGLE_QUOTES: "''" >
    | < #CONTROL_STRING: "'" ("#" ( <DIGIT> )+ )* "'" >


    // Strings
    | < STRING: "'" ( ~["'"] | <SINGLE_QUOTES> | <CONTROL_STRING> )* "'" >

    // Numbers
    | < REAL: ( <SIGN> )? ( <DIGIT> )+ "." ( <DIGIT> )* >
    | < INTEGER: ( <SIGN> )? ( <DIGIT> )+ >
    | < HEXADECIMAL: ( <SIGN> )? "$" (<DIGIT> | <LETTER_HEXADECIMAL>)+ >
    | < OCTAL: ( <SIGN> )? "&" (<OCTAL_DIGIT>)+ >
    | < BINARY: ( <SIGN> )? "%" (<BINARY_DIGIT>)+ >
    | < EXPONENTIAL: ( <SIGN> )? ( ( <DIGIT> )+ (["e","E"]) ( <SIGN> )? ( <DIGIT> )+ ) >
    
    // Identificadores
    | < ID: <LETTER> ( <LETTER> | <DIGIT> )* >
    | < ESCAPED_ID: "&" <LETTER> ( <LETTER> | <DIGIT> )* >
}

/* testar:
    < COMMENT_MULTIPLE_LINES: ( ("{" (~["}"])* "}")+ | ("(*" (~["}"])* "*)")+ ) >
  | < COMMENT_SINGLE_LINE: "//" (~["\n", "\r"])* >
*/

/* The regular expressions here will be skipped during lexical analysis: */
SKIP : {
    < COMMENT_MULTIPLE_LINES: ( "{" (~["}"])* "}" )+ | ( "(*" ( ~["*", ")"] )* "*)" )+ >
    | < COMMENT_SINGLE_LINE: "//" (~["\n", "\r"])* >
    | ""
    | "\t"
    | "\n"
}

/* If we have a substring that does not match any of the regular expressions in TOKEN or SKIP,
JavaCC will automatically throw an error. */

void Start() :
{}
{
    {
        Token t;
        do {
            t = getNextToken();
            System.out.println("Token: " + t.image + " | Tipo: " + tokenImage[t.kind]);
        } while (t.kind != 0); // 0 = EOF
    }
}


